name: false positive ops

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'FP Report') 
    steps:
      - uses: actions/checkout@v2
        with:
          path: odc
      - name: directory listing
        run: |
          ls
          echo "----------"
          ls odc
      - name: Parse False Positive Issue
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: odc/.github/ISSUE_TEMPLATE/false-positive-report.yml
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Initialize npm
        run: |
          npm init -y
          npm install packageurl-js
      - name: Parse Package URL
        uses: actions/github-script@v6
        id: purl-parser
        with:
          script: |
            try {
            const { PackageURL } = require('packageurl-js');
            const pkg = PackageURL.fromString('${{ fromJSON(steps.issue-parser.outputs.jsonString).purl }}');
            console.log(pkg);
            return pkg;
            } catch (ex) {
              console.log(ex);
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Error parsing package url: ' + ex
              })
            }
