name: false positive ops

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'FP Report') 
    steps:
      - name: Parse Issue Body
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/false-positive-report.yml

      - name: issue context
        run: |
          echo "${{github.event.issue}}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "---------------------"
          echo "---------------------"
          echo "parsed: ${{ steps.issue-parser.outputs }}"
          echo "---------------------"
          echo "---------------------"
