name: ODC Test
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Check Maven Cache
        id: maven-cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository/
          key: mvn-repo
      - name: Set up JDK 1.8
        id: jdk-8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: maven verify
        id: build
        run: |
            mvn verify --no-transfer-progress --batch-mode
      - name: Upload sarif report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: src/test/resources/dependency-check-report.sarif